version: "1"
services: 
  frontend:
    container_name: bayview-production
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000